//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace ShippingService.Business.CarrierServices.TNT.Price.PriceResponse {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class document {
        
        private string requestIdField;
        
        private errors errorsField;
        
        private priceResponse[] priceResponseField;
        
        /// <remarks/>
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public errors errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("priceResponse")]
        public priceResponse[] priceResponse {
            get {
                return this.priceResponseField;
            }
            set {
                this.priceResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class errors {
        
        private runtimeError[] runtimeErrorField;
        
        private parseError[] parseErrorField;
        
        private brokenRule[] brokenRuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("runtimeError")]
        public runtimeError[] runtimeError {
            get {
                return this.runtimeErrorField;
            }
            set {
                this.runtimeErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parseError")]
        public parseError[] parseError {
            get {
                return this.parseErrorField;
            }
            set {
                this.parseErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brokenRule")]
        public brokenRule[] brokenRule {
            get {
                return this.brokenRuleField;
            }
            set {
                this.brokenRuleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runtimeError {
        
        private string errorReasonField;
        
        private string errorSrcTextField;
        
        /// <remarks/>
        public string errorReason {
            get {
                return this.errorReasonField;
            }
            set {
                this.errorReasonField = value;
            }
        }
        
        /// <remarks/>
        public string errorSrcText {
            get {
                return this.errorSrcTextField;
            }
            set {
                this.errorSrcTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class chargeElement {
        
        private int chargeItemField;
        
        private string chargeCategoryField;
        
        private string chargeCodeField;
        
        private string descriptionField;
        
        private decimal chargeValueField;
        
        private bool vatIndicatorField;
        
        /// <remarks/>
        public int chargeItem {
            get {
                return this.chargeItemField;
            }
            set {
                this.chargeItemField = value;
            }
        }
        
        /// <remarks/>
        public string chargeCategory {
            get {
                return this.chargeCategoryField;
            }
            set {
                this.chargeCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string chargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal chargeValue {
            get {
                return this.chargeValueField;
            }
            set {
                this.chargeValueField = value;
            }
        }
        
        /// <remarks/>
        public bool vatIndicator {
            get {
                return this.vatIndicatorField;
            }
            set {
                this.vatIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class option {
        
        private string optionCodeField;
        
        private string optionDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string optionCode {
            get {
                return this.optionCodeField;
            }
            set {
                this.optionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string optionDesc {
            get {
                return this.optionDescField;
            }
            set {
                this.optionDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class options {
        
        private option[] optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public option[] option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product {
        
        private string idField;
        
        private string divisionField;
        
        private string productDescField;
        
        private string typeField;
        
        private options optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productDesc {
            get {
                return this.productDescField;
            }
            set {
                this.productDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public options options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ratedService {
        
        private product productField;
        
        private decimal totalPriceField;
        
        private decimal totalPriceExclVatField;
        
        private decimal vatAmountField;
        
        private chargeElement[] chargeElementsField;
        
        /// <remarks/>
        public product product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalPriceExclVat {
            get {
                return this.totalPriceExclVatField;
            }
            set {
                this.totalPriceExclVatField = value;
            }
        }
        
        /// <remarks/>
        public decimal vatAmount {
            get {
                return this.vatAmountField;
            }
            set {
                this.vatAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public chargeElement[] chargeElements {
            get {
                return this.chargeElementsField;
            }
            set {
                this.chargeElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ratedServices {
        
        private string rateIdField;
        
        private string currencyField;
        
        private ratedService[] ratedServiceField;
        
        /// <remarks/>
        public string rateId {
            get {
                return this.rateIdField;
            }
            set {
                this.rateIdField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ratedService")]
        public ratedService[] ratedService {
            get {
                return this.ratedServiceField;
            }
            set {
                this.ratedServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class priceResponse {
        
        private ratedServices ratedServicesField;
        
        /// <remarks/>
        public ratedServices ratedServices {
            get {
                return this.ratedServicesField;
            }
            set {
                this.ratedServicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class brokenRule {
        
        private string rateIdField;
        
        private string messageTypeField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string rateId {
            get {
                return this.rateIdField;
            }
            set {
                this.rateIdField = value;
            }
        }
        
        /// <remarks/>
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parseError {
        
        private string errorReasonField;
        
        private string errorLineField;
        
        private string errorLineposField;
        
        private string errorSrcTextField;
        
        /// <remarks/>
        public string errorReason {
            get {
                return this.errorReasonField;
            }
            set {
                this.errorReasonField = value;
            }
        }
        
        /// <remarks/>
        public string errorLine {
            get {
                return this.errorLineField;
            }
            set {
                this.errorLineField = value;
            }
        }
        
        /// <remarks/>
        public string errorLinepos {
            get {
                return this.errorLineposField;
            }
            set {
                this.errorLineposField = value;
            }
        }
        
        /// <remarks/>
        public string errorSrcText {
            get {
                return this.errorSrcTextField;
            }
            set {
                this.errorSrcTextField = value;
            }
        }
    }
}
