//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteServices.Client.TIMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TIMService.ITIMService")]
    public interface ITIMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIMService/GetInventory", ReplyAction="http://tempuri.org/ITIMService/GetInventoryResponse")]
        byte[] GetInventory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIMService/GetOrderConfirmations", ReplyAction="http://tempuri.org/ITIMService/GetOrderConfirmationsResponse")]
        byte[] GetOrderConfirmations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIMService/MarkOrderConfirmation", ReplyAction="http://tempuri.org/ITIMService/MarkOrderConfirmationResponse")]
        bool MarkOrderConfirmation(out string error, string orderId, string lineNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIMService/MarkShippingConfirmation", ReplyAction="http://tempuri.org/ITIMService/MarkShippingConfirmationResponse")]
        bool MarkShippingConfirmation(out string error, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIMService/GetShippingConfirmations", ReplyAction="http://tempuri.org/ITIMService/GetShippingConfirmationsResponse")]
        byte[] GetShippingConfirmations();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITIMServiceChannel : RemoteServices.Client.TIMService.ITIMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TIMServiceClient : System.ServiceModel.ClientBase<RemoteServices.Client.TIMService.ITIMService>, RemoteServices.Client.TIMService.ITIMService {
        
        public TIMServiceClient() {
        }
        
        public TIMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TIMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TIMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TIMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetInventory() {
            return base.Channel.GetInventory();
        }
        
        public byte[] GetOrderConfirmations() {
            return base.Channel.GetOrderConfirmations();
        }
        
        public bool MarkOrderConfirmation(out string error, string orderId, string lineNumber) {
            return base.Channel.MarkOrderConfirmation(out error, orderId, lineNumber);
        }
        
        public bool MarkShippingConfirmation(out string error, string orderId) {
            return base.Channel.MarkShippingConfirmation(out error, orderId);
        }
        
        public byte[] GetShippingConfirmations() {
            return base.Channel.GetShippingConfirmations();
        }
    }
}
